#pragma once
#include <Uefi.h>
#include <Library/BaseLib.h>

typedef EFI_STATUS CR_STATUS;
#define CR_SUCCESS EFI_SUCCESS
#define CR_ERROR EFI_ABORTED
#define CR_INVALID_PARAMETER EFI_INVALID_PARAMETER
#define CR_NOT_FOUND EFI_NOT_FOUND
#define CR_OUT_OF_RESOURCES EFI_OUT_OF_RESOURCES
#define CR_UNSUPPORTED EFI_UNSUPPORTED
#define CR_DEVICE_ERROR EFI_DEVICE_ERROR
#define CR_TIMEOUT EFI_TIMEOUT